services:
  frontend:
    image: prashantkatare/frontend:1
    ports:
      - "80:80"
    networks:
      - front-tier
      - back-tier
  backend:
    image: prashantkatare/backend:1
    ports:
      - "3000:3000"
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier:

##
